fuse_getattr: send fh in request when revise attr in read or write
boyuan-he/gvisor pull request #9
Opened 2020-08-31 18:03 UTC by craig08

1. Add a fuse_util function to return a default `fuse_attr` for a nodeid and mode.
2. Add fh support in FUSE_GETATTR. According to Linux 4.4's FUSE behavior, the flags and fh attributes in FUSE_GETATTR are only used in read, write, and lseek. `fstat(2)` doesn't use them either.
3. Add a test to ensure the request of `fstat(2)` sent from FUSE module is consistent with Linux's.

2020-09-02 21:15 UTC, jinmouil commented
For 120a6039cfb3e8226370a4ab513b1d7122417c03 , I'd recommend against testing such behavior. It's not documented anywhere and it's not a part of the protocol

2020-09-02 21:37 UTC, jinmouil commented
Also `write` does not call `GETATTR` at all. It simply changes the inode size if write beyond EOF and mark all those as invalid (fuse_invalidate_attr(inode))

2020-09-03 19:52 UTC, craig08 commented
> For [120a603](https://github.com/boyuan-he/gvisor/commit/120a6039cfb3e8226370a4ab513b1d7122417c03) , I'd recommend against testing such behavior. It's not documented anywhere and it's not a part of the protocol, which means any update in the future is free to change it without notification

Added a test for calling GETATTR with fh.

2020-09-04 00:03 UTC, jinmouil requested changes

2020-09-04 00:03 UTC, jinmouil commented on test/fuse/linux/stat_test.cc
> +  // Do integration test.
This comment actually does not introduce new information

How about `Make syscall.`

2020-09-04 00:03 UTC, jinmouil commented on pkg/abi/linux/fuse.go
> +const FUSE_GETATTR_FH = (1 << 0)
Exported variable should have comments

2020-09-04 00:03 UTC, jinmouil commented on pkg/sentry/fsimpl/fuse/regular_file.go
> +		if err := inode.reviseAttr(ctx, linux.FUSE_GETATTR_FH, fd.Fh); err != nil {
Is FUSE_GETATTR_FH flag or fh? Sorry I'm confused

2020-09-04 00:03 UTC, jinmouil commented on test/fuse/linux/stat_test.cc
> +  // will be issued after read completes.
`after`?

2020-09-04 00:53 UTC, craig08 commented on pkg/sentry/fsimpl/fuse/regular_file.go
> +		if err := inode.reviseAttr(ctx, linux.FUSE_GETATTR_FH, fd.Fh); err != nil {
It's a flag.

2020-09-09 17:05 UTC, merged